const Router = require('express')
const router = new Router()
const workerRouter = require('./worker')
const projectRouter = require('./project')
const roleRouter = require('./role')
const usersRouter = require('./users')
const techAspectRouter = require('./techAspect')
const techSpecificationRouter = require('./techSpecification')
const technologyRouter = require('./technology')
const project_technologyRouter = require('./project_technology')
const worker_technologyRouter = require('./worker_technology')
const role_projectRouter = require('./role_project')

router.use('/Worker', workerRouter)
router.use('/Project', projectRouter)
router.use('/Role', roleRouter)
router.use('/Users', usersRouter)
router.use('/TechAspect', techAspectRouter)
router.use('/TechSpecification', techSpecificationRouter)
router.use('/Technology', technologyRouter)
router.use('/Project_Technology', project_technologyRouter)
router.use('/Worker_Technology', worker_technologyRouter)
router.use('/Role_Project', role_projectRouter)

module.exports = router